set colorcolumn=80
set tabstop=4 softtabstop=0
set shiftwidth=4
set expandtab
set textwidth=75

" shamelessly stolen from Curt's stuff
function! WordProcessorMode()
    setlocal wrap scrolloff=0 linebreak nolist colorcolumn=
    setlocal spell spelllang=en_us
    set showbreak=┊
    " Up/down move screen lines, not file lines
    noremap j gj
    noremap k gk
    echo "Word Processor mode."
endfunction

map gqq {!}par -w75<CR>
